### ISSUE TITLE
GFM tables not converting to html correctly

### ISSUE THREAD

**Issue by samhstn** [elm-explorations/markdown#2]
Running the following program:

```elm
module Main exposing (main)

import Markdown


main =
    Markdown.toHtml
        []
        md


md : String
md =
    """
|title|
|-|
|content|
"""
```

Currently outputs in the browser:

`<div><p>|title| |-| |content|</p></div>`

Expected output in the browser:

`<table><thead><tr><th>title</th></tr></thead><tbody><tr><td>content</td></tr></tbody></table>`

The marked library at [`cd2f6f5b7091154c5526e79b5f3bfb4d15995a51`](https://github.com/elm-explorations/markdown/blob/master/src/Elm/Kernel/Markdown.js#L69) facilitates this

```node
const marked = require('marked');

const md = `
|title|
|-|
|content|
`

console.log(marked(md)) // => <table><thead><tr><th>title</th></tr></thead><tbody><tr><td>content</td></tr></tbody></table>
```

**Comment by rlefevre** [comment]
`elm-explorations/markdown` is actually based on the [marked](https://github.com/markedjs/marked) library. Tables however is an option that is enabled by default in marked and disabled by default in `elm-explorations/markdown`. 
You can enable them with [toHtmlWith](https://package.elm-lang.org/packages/elm-explorations/markdown/latest/Markdown#toHtmlWith), for example:

```
module Main exposing (main)

import Markdown exposing (defaultOptions)


main =
    Markdown.toHtmlWith
        { defaultOptions | githubFlavored = Just { tables = True, breaks = False } }
        []
        md


md : String
md =
    """
|title|
|-|
|content|
"""
```
which will output as expected:
```
<table><thead><tr><th>title</th></tr></thead><tbody><tr><td>content</td></tr></tbody></table>
```
See [marked options](https://marked.js.org/#/USING_ADVANCED.md#options) and [elm-explorations/markdown options](https://package.elm-lang.org/packages/elm-explorations/markdown/latest/Markdown#Options).

**Comment by samhstn** [comment]
Thanks for the quick reply @rlefevre  👍

Works as described in [docs](https://package.elm-lang.org/packages/elm-explorations/markdown/latest/Markdown#Options), closing
